//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Taksi.rc
//
#define ID_APP                          100
#define IDS_STRING101                   101
#define IDS_HELP_CODEC_CRAM             101
#define IDS_HELP_CODEC_DIB              102
#define IDS_HELP_CODEC_FAIL             103
#define IDS_ERR_SAVEDIR                 104
#define IDS_HELP_CAPTURE                105
#define IDD_GuiConfig                   110
#define IDD_GuiConfigTab1               111
#define IDD_GuiConfigTab2               112
#define IDD_GuiConfigTab3               113
#define IDD_GuiConfigTab4               114
#define IDD_GuiConfigTab5               115
#define IDD_GuiConfigTab6               116
#define IDD_About                       143
#define IDM_TRAYICON                    150
#define IDC_SHOW_NORMAL                 151
#define IDB_ConfigOpen_1                200
#define IDB_HookModeToggle_1            201
#define IDB_IndicatorToggle_1           202
#define IDB_RecordBegin_1               203
#define IDB_RecordPause_1               204
#define IDB_RecordStop_1                205
#define IDB_Screenshot_1                206
#define IDB_SmallScreenshot_1           207
#define IDB_RecordBegin_G               208
#define IDB_RecordPause_G               209
#define IDB_RecordStop_G                210
#define IDB_Screenshot_G                211
#define IDB_SmallScreenshot_G           212
#define IDB_HookModeToggle_2            213
#define IDB_IndicatorToggle_2           214
#define IDB_RecordPause_2               215
#define IDB_HookModeToggle_3            216
#define IDC_ABOUT_1                     1001
#define IDC_ABOUT_4                     1004
#define IDC_ABOUT_5                     1005
#define IDC_C_TAB                       1009
#define IDC_C_StatusText                1010
#define IDC_C_RestoreButton             1011
#define IDC_C_SaveButton                1012
#define IDC_C_CaptureDirectory          1020
#define IDC_C_CaptureDirectoryBrowse    1021
#define IDC_C_CaptureDirectoryExplore   1022
#define IDC_C_DebugLog                  1023
#define IDC_C_FileNamePostfix           1024
#define IDC_C_FrameRate                 1030
#define IDC_C_VideoCodecButton          1031
#define IDC_C_VideoCodec                1032
#define IDC_C_VideoHalfSize             1033
#define IDC_C_AudioDevices              1034
#define IDC_C_AudioCodecButton          1035
#define IDC_C_AudioCodec                1036
#define IDC_C_KeyConfigOpen             1040
#define IDC_C_KeyHookModeToggle         1041
#define IDC_C_KeyIndicatorToggle        1042
#define IDC_C_KeyRecordBegin            1043
#define IDC_C_KeyRecordPause            1044
#define IDC_C_KeyRecordStop             1045
#define IDC_C_KeyScreenshot             1046
#define IDC_C_KeySmallScreenshot        1047
#define IDC_C_UseDirectInput            1048
#define IDC_C_CustomSettingsList        1050
#define IDC_C_CustomPattern             1051
#define IDC_C_CustomFrameRate           1052
#define IDC_C_CustomFrameWeight         1053
#define IDC_C_CustomNewButton           1054
#define IDC_C_CustomDeleteButton        1055
#define IDC_C_CustomUseCurrent          1056
#define IDC_C_StatProcessName           1060
#define IDC_C_StatLastError             1061
#define IDC_C_StatState                 1062
#define IDC_C_StatFrameRate             1063
#define IDC_C_StatDataRecorded          1064
#define IDC_C_StatFormat                1065
#define IDC_C_StatGAPI                  1066
#define IDC_C_StatsClear                1067
#define IDC_C_UseOverheadCompensation   1071
#define IDC_C_GDIDesktop                1072
#define IDC_C_GDIFrame                  1073
#define IDC_C_MasterTopMost             1074
#define IDC_C_UseGDI                    1075
#define IDC_C_UseOGL                    1076
#define IDC_C_UseDX8                    1077
#define IDC_C_UseDX9                    1078
#define IDC_C_GDICursor					1079
#define IDS_APP_DESC                    2000
#define IDS_GuiConfigHelp1              2010
#define IDS_GuiConfigHelp2              2011
#define IDS_GuiConfigHelp3              2012
#define IDS_GuiConfigHelp4              2013
#define IDS_GuiConfigHelp5              2014
#define IDS_GuiConfigHelp6              2015
#define IDS_STATE_Idle					2020
#define IDS_STATE_Hooked                2021
#define IDS_STATE_Ready                 2022
#define IDS_STATE_Recording             2023
#define IDS_STATE_RecordPause           2024
#define IDS_STATE_QTY                   2025
#define IDS_STATUS_CHANGES              2101
#define IDS_STATUS_RESTORED             2102
#define IDS_STATUS_SAVED                2103
#define IDS_STATUS_FAILSAVE             2104
#define IDS_SELECT_APP_HOOK             2106
#define IDM_SC_HELP_URL                 0xE000
#define IDM_SC_HELP_ABOUT               0xE010
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         40011
#define _APS_NEXT_CONTROL_VALUE         1090
#define _APS_NEXT_SYMED_VALUE           10005
#endif
#endif
